# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=45, verbose_name='Assunto')),
                ('data', models.DateTimeField(verbose_name='dt.Agendamento')),
                ('horaEntrada', models.TimeField(verbose_name='hora.Entrada')),
                ('horaSaida', models.TimeField(verbose_name='hora_Saida')),
                ('instituicao', models.CharField(max_length=45, verbose_name='Instituicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
        migrations.CreateModel(
            name='Bo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text=' 100 caracteres ou menos.', max_length=100, verbose_name='T\xedtulo')),
                ('impacto', models.CharField(choices=[('1', 'Muito baixo'), ('2', 'Baixo'), ('3', 'M\xe9dio'), ('4', 'Alto'), ('5', 'Muito alto')], default='1', max_length=1, verbose_name='Impacto')),
                ('texto', models.TextField(help_text='500 caracteres ou menos.', max_length=500, verbose_name='Texto')),
                ('data', models.DateTimeField(verbose_name='')),
                ('administrador', models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Boletins',
            },
        ),
        migrations.CreateModel(
            name='CategoriaBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='45 caracteres ou menos.', max_length=45, verbose_name='Categoria')),
            ],
            options={
                'db_table': 'categoriaBos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Obrigat\xf3rio. 45 caracteres ou menos.', max_length=45, verbose_name='Categoria')),
            ],
            options={
                'db_table': 'categoriaNoticia',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='100 caracteres ou menos.', max_length=100, verbose_name='T\xedtulo')),
                ('descricao', models.TextField(help_text='500 caracteres ou menos.', max_length=500, verbose_name='Descri\xe7\xe3o')),
                ('imagem', models.ImageField(upload_to=b'', verbose_name='Imagem')),
                ('data', models.DateTimeField(verbose_name='Publica\xe7\xe3o')),
                ('texto', models.TextField(help_text='2048 caracteres ou menos.', max_length=2048, verbose_name='Texto')),
                ('status', models.BooleanField(default='False', verbose_name='Publicada')),
                ('administrador', models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortalPopAc.CategoriaNoticia')),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('sigla', models.CharField(help_text='Obrigat\xf3rio. 6 caracteres ou menos.', max_length=6, primary_key='true', serialize=False, verbose_name='Sigla')),
                ('site', models.CharField(help_text='45 caracteres ou menos.', max_length=45, verbose_name='Site')),
                ('contato', models.CharField(help_text='45 caracteres ou menos.', max_length=45, verbose_name='Contato')),
            ],
            options={
                'db_table': 'pops',
            },
        ),
        migrations.AddField(
            model_name='bo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortalPopAc.CategoriaBo'),
        ),
    ]
